# Generated by Django 5.2.5 on 2025-08-12 11:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dietary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "price_per_100g",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price per 100 g",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "allergen",
                    models.SlugField(
                        blank=True,
                        choices=[
                            ("peanut", "peanut"),
                            ("soy", "soy"),
                            ("milk", "milk"),
                            ("egg", "egg"),
                            ("wheat", "wheat"),
                            ("gluten", "gluten"),
                            ("tree-nut", "tree-nut"),
                            ("almond", "almond"),
                            ("cashew", "cashew"),
                            ("pistachio", "pistachio"),
                            ("walnut", "walnut"),
                            ("sesame", "sesame"),
                            ("fish", "fish"),
                            ("shellfish", "shellfish"),
                        ],
                    ),
                ),
                (
                    "energy_kj",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "protein",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("fat", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "carbs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fiber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "dietaries",
                    models.ManyToManyField(
                        blank=True, related_name="ingredients", to="kaiapp.dietary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "dietary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kaiapp.dietary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_g",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kaiapp.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="kaiapp.meal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meal",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="meals",
                through="kaiapp.RecipeIngredient",
                to="kaiapp.ingredient",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="uniq_recipe_ingredient"
            ),
        ),
    ]
