# Generated by Django 5.2.5 on 2025-08-12 11:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kaiapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="price_per_100g",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price per 100 g",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
