# Generated by Django 5.2.5 on 2025-08-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kaiapp", "0002_alter_ingredient_price_per_100g"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="name",
            field=models.CharField(max_length=160),
        ),
    ]
